---
# upstream expects enable_snat to be defaulted to true, but in OTC it is not that
# therefore it is required to enable snat manually later or use heat
- name: Create Router
  os_router:
    name: "{{ router_name }}"
    state: "{{ state }}"
    network: "{{ external_network_name }}"
    enable_snat: "{{ enable_snat }} "
    interfaces:
      - net: "{{ network_name }}"
        subnet: "{{ subnet_name }}"
  register: net_router
  when: state != 'absent'

- name: Assert that SNAT is as requested
  assert:
    that:
      - net_router.router.external_gateway_info.enable_snat == enable_snat
  when: state != 'absent'

- name: Delete Router
  os_router:
    name: "{{ router_name }}"
    state: "{{ state }}"
  when: state == 'absent'
